DROP TABLE IF EXISTS CLIENTE_OFERTA_SERVICO;
DROP TABLE IF EXISTS CLIENTE_MORA;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS SERVICO;


CREATE TABLE CLIENTE(
	CPF varchar(20) NOT NULL,
    DATA_NASCIMENTO DATE,
    EMAIL VARCHAR(100),
    NOME VARCHAR(80),
	GENERO INTEGER,
    SENHA VARCHAR(100),
    TELEFONE VARCHAR(15),
    
    PRIMARY KEY(CPF)
);

CREATE TABLE SERVICO(
	ID INTEGER NOT NULL,
    NOME_SERVICO VARCHAR(200),
    DESCRICAO VARCHAR(244),
	
    
    PRIMARY KEY (ID)
);

CREATE TABLE CLIENTE_OFERTA_SERVICO(
	CPF_CLIENTE VARCHAR(20) NOT NULL,
    ID_SERVICO INTEGER NOT NULL,
    
    PRIMARY KEY(CPF_CLIENTE,ID_SERVICO),
    FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTE(CPF),
    FOREIGN KEY (ID_SERVICO) REFERENCES SERVICO(ID)

);

CREATE TABLE CLIENTE_MORA(
	CPF_CLIENTE VARCHAR(20) NOT NULL, 
    CEP CHAR(8) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
    ESTADO VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
	RUA VARCHAR(30),
    NUMERO_LOGRADOURO VARCHAR(10),
    
    PRIMARY KEY(CPF_CLIENTE),
    FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTE(CPF)
);
